In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray()) ## slightly different from what i wrote in notebook since in this case they are assigning the frequency by the index values.
## so in 'people watch campusx' since campusx index is 0 we check if it is present which is yes with frequency 1.
## second index is comment not present so 0
## third index is people present with 1 frequency so 1
## 4th index watch present with frequency 1.
## 5th index is write not present.

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [ ]:
cv.transform(['campusx watch and write comment of campusx']).toarray() ## It handles out of vocabulary word as well. 'and' 'of' are handled.

array([[2, 1, 0, 1, 1]])

### N-Grams

In [11]:
ngram = CountVectorizer(ngram_range=(2,2)) ## Bi-Gram
bow = ngram.fit_transform(df['text'])

In [12]:
print(ngram.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [ ]:
ngram = CountVectorizer(ngram_range=(1,2)) ## Both features of unigram and bigram as well ## it takes unigram features as well.
bow = ngram.fit_transform(df['text'])

In [15]:
print(ngram.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [16]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 1 1 0 1 1 0 0]]
[[2 1 0 0 0 0 0 1 1 0 0]]


### TFIDF

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()

tf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [19]:
print(tf.idf_)
print(tf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
