In [2]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 75.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 95.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 18.2 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.0
    Uninstalling scipy-1.16.0:
      Successfully uninstalled scipy-1.16.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatib

In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [6]:
!git clone https://huggingface.co/fse/word2vec-google-news-300
!cd word2vec-google-news-300

Cloning into 'word2vec-google-news-300'...
remote: Enumerating objects: 11, done.
remote: Total 11 (delta 0), reused 0 (delta 0), pack-reused 11 (from 1)
Unpacking objects: 100% (11/11), 1.51 KiB | 773.00 KiB/s, done.
Filtering content: 100% (2/2), 3.52 GiB | 36.60 MiB/s, done.


In [9]:
model = KeyedVectors.load("/content/word2vec-google-news-300/word2vec-google-news-300.model")

In [12]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [13]:
model['man'].shape

(300,)

In [14]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [15]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [16]:
model.similarity('man','woman') ## checks cosine similarity between the two words by converting them into vectors

0.76640123

In [17]:
model.similarity('man','PHP')

-0.032995153

In [18]:
model.doesnt_match(['PHP','java','monkey']) ## finds the odd one out

'monkey'

In [19]:
## Vector arithmetic
vec = model['king'] - model['man'] + model['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [20]:
model.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [21]:
##
model.most_similar(positive=['king','woman'],negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

In [22]:
model.most_similar(positive=['INR','England'],negative=['India'])

[('GBP', 0.46803125739097595),
 ('£_##.###m', 0.4423891603946686),
 ('ticker_symbol_BNK', 0.41698920726776123),
 ('£', 0.41218066215515137),
 ('£_#.##m', 0.4115550220012665),
 ('FOOTBALL_::', 0.4112643897533417),
 ('Â_£', 0.4065624475479126),
 ('stg###', 0.4061710238456726),
 ('stock_symbol_BNK', 0.40497055649757385),
 ('£_4m', 0.40464991331100464)]

In [23]:
vec1 = model['INR'] - model['India'] + model['England']
vec1

array([ 0.0402832 ,  0.06433105, -0.08557129,  0.26586914,  0.23339844,
        0.00976562,  0.01049805, -0.18261719,  0.27368164, -0.07946777,
       -0.20568848, -0.14550781, -0.26123047,  0.12817383,  0.1428833 ,
        0.17749023, -0.41516113, -0.10693359, -0.02166748, -0.16918945,
       -0.08747292, -0.121521  , -0.09388733, -0.05371094, -0.07080078,
        0.08740234, -0.42382812,  0.22216797,  0.09155273,  0.08203125,
        0.03320312, -0.18804932,  0.01074219, -0.20489502, -0.48254395,
       -0.35302734,  0.10583496, -0.48754883, -0.2607422 ,  0.13061523,
       -0.02258301, -0.2434082 ,  0.2770996 , -0.26611328, -0.29370117,
       -0.03344727,  0.3380127 ,  0.33007812, -0.4663086 , -0.01757812,
       -0.01928711,  0.28759766,  0.14305878, -0.13842773, -0.12353516,
       -0.07446289,  0.10253906,  0.23822021,  0.00585938, -0.00488281,
       -0.19281006, -0.02148438, -0.05444336, -0.22021484,  0.14160156,
       -0.12524414,  0.00708008,  0.20166016, -0.0279541 ,  0.14

In [24]:
model.most_similar(vec1)

[('INR', 0.6442341208457947),
 ('GBP', 0.5040826797485352),
 ('£_##.###m', 0.4540838301181793),
 ('England', 0.44649264216423035),
 ('£', 0.43340998888015747),
 ('Â_£', 0.4307197630405426),
 ('stg###', 0.4299262464046478),
 ('£_#.##m', 0.42561301589012146),
 ('Pounds_Sterling', 0.42512619495391846),
 ('GBP##', 0.42464491724967957)]

In [ ]:
# Manual vector arithmetic (e.g. king - man + woman) treats each vector equally and directly, 
# while most_similar(positive=['king', 'woman'], negative=['man'])
#internally averages the positive vectors before subtracting the negatives. This subtle difference can lead to different results.
#Which is better?
# The positive/negative method is preferred — it’s more stable, normalized, and accounts for multiple words naturally. 
# Use manual arithmetic only when you need full control over the math.