In [ ]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 89.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 15.8 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.0
    Uninstalling scipy-1.16.0:
      Successfully uninstalled scipy-1.16.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
openc

In [ ]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king = wv['king'] ## This is how we can import the pretrained model of Google News.
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
### Let's Start with Word2Vec Model of our own.
import pandas as pd
messages = pd.read_csv('/content/SMSSpamCollection.txt',sep='\t',names=['label','messages'])

In [ ]:
messages.shape

(5572, 2)

In [ ]:
messages.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
### Text Preprocessing
messages.isnull().sum()

label       0
messages    0
dtype: int64

In [ ]:
messages.label.value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stop

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [ ]:
len(messages)
# corpus = []
# for i in range(0, len(messages)):
#     review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
#     review = review.lower()
#     review = review.split()

#     review = [lemmatizer.lemmatize(word) for word in review]
#     review = ' '.join(review)
#     corpus.append(review)

5572

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
corpus = []
for doc in messages['messages']:
  doc = re.sub('[^a-zA-Z]',' ',doc)
  doc = doc.lower()
  doc = doc.split()
  doc = [lem.lemmatize(word) for word in doc if word not in stop]
  corpus.append(doc)

In [ ]:
empty_docs = [i for i, doc in enumerate(corpus) if len(doc) == 0]

print(f"Number of empty documents: {len(empty_docs)}")

Number of empty documents: 8


In [ ]:
print(f"Indices of empty documents: {empty_docs}")

Indices of empty documents: [253, 960, 1612, 2807, 3376, 4117, 4575, 4824]


In [ ]:
corpus = [doc for doc in corpus if doc]

In [ ]:
empty_docs = [i for i, doc in enumerate(corpus) if len(doc) == 0]

print(f"Number of empty documents: {len(empty_docs)}")

Number of empty documents: 0


In [ ]:
print(f"Indices of empty documents: {empty_docs}")

Indices of empty documents: []


In [ ]:
len(corpus)

5564

In [ ]:
### Let's train the model
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)
# Min frequency for a word to be included	Filters out rare/unimportant words

In [ ]:
model.build_vocab(corpus)

In [ ]:
model.train(corpus,total_examples=model.corpus_count,epochs=model.epochs)

(211980, 251605)

In [ ]:
len(model.wv.index_to_key)

3571

In [ ]:
def document_vector(doc):
    words = [word for word in doc.split() if word in model.wv.index_to_key]
    if not words:
        return np.zeros(model.vector_size)  # or np.nan * np.ones(model.vector_size)
    return np.mean(model.wv[words], axis=0)

In [ ]:
document_vector(messages['messages'].values[0])

array([-3.18107784e-01,  3.80363077e-01,  3.89056839e-02, -2.32351702e-02,
        1.20577231e-01, -7.76423931e-01,  2.03839168e-01,  9.96333718e-01,
       -2.99724758e-01, -3.08570445e-01, -2.78158844e-01, -4.41138446e-01,
       -1.03541993e-01,  1.81961805e-01,  1.61051959e-01, -2.86929429e-01,
        6.87242523e-02, -5.71183443e-01, -3.39299291e-02, -8.11462522e-01,
        2.98313469e-01,  2.74296373e-01,  2.57700950e-01, -2.48163179e-01,
       -9.75989848e-02, -9.45728123e-02, -1.31410912e-01, -2.29746461e-01,
       -3.66205454e-01,  1.10112146e-01,  3.78186941e-01,  3.55455801e-02,
        1.41467243e-01, -1.98380455e-01, -1.69668317e-01,  3.80806804e-01,
        9.25434381e-02, -5.68037152e-01, -1.17828980e-01, -8.13870192e-01,
        7.04661384e-02, -4.31892663e-01, -1.29882187e-01, -1.25908300e-01,
        4.80749428e-01, -1.89342037e-01, -3.19084197e-01, -1.75291777e-01,
        2.24655375e-01,  3.34903359e-01,  2.07343429e-01, -2.56875813e-01,
       -2.41857007e-01, -

In [ ]:
!pip install tqdm

In [ ]:
from tqdm import tqdm ## tqdm is only for the progress bar.
X =[]
for doc in tqdm(messages['messages'].values):
    X.append(document_vector(doc))

100%|██████████| 5572/5572 [00:04<00:00, 1319.79it/s]


In [ ]:
len(X)

5572

In [ ]:
X_nonzero = [vec for vec in X if not np.all(vec == 0)]

In [ ]:
len(X_nonzero)

5130

In [ ]:
X_input = np.array(X_nonzero)

In [ ]:
X_input.shape

(5130, 100)

In [ ]:
len(X)

5572

In [ ]:
nonzero_indices = [i for i, vec in enumerate(X) if not np.all(vec == 0)]

In [ ]:
y_clean = messages['label'].iloc[nonzero_indices].reset_index(drop=True)

In [ ]:
len(y_clean)

5130

In [ ]:
y_clean

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5125    spam
5126     ham
5127     ham
5128     ham
5129     ham
Name: label, Length: 5130, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_clean=le.fit_transform(y_clean)

In [ ]:
y_clean

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_input,y_clean,test_size=0.2,random_state=42)

In [ ]:
X_train.shape,X_test.shape

((4104, 100), (1026, 100))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9434697855750487
[[861  13]
 [ 45 107]]


In [ ]:
document_vector('Hey this is a big billion sales offer you have won a lottery').reshape(1,-1)

array([[-0.17595653,  0.20423342,  0.01767281, -0.01844996,  0.07340631,
        -0.42769942,  0.10879302,  0.5440277 , -0.17043263, -0.16702807,
        -0.15126349, -0.24759698, -0.06232338,  0.10802352,  0.0800086 ,
        -0.15608664,  0.0365858 , -0.30987462, -0.0238702 , -0.44629213,
         0.1605003 ,  0.15223773,  0.14491214, -0.1355113 , -0.05197917,
        -0.04574372, -0.07816239, -0.12286622, -0.20340173,  0.05312129,
         0.21040459,  0.0134638 ,  0.07594264, -0.10480269, -0.09271261,
         0.20731854,  0.05194305, -0.31666037, -0.06324846, -0.45103645,
         0.03548352, -0.23688321, -0.07452074, -0.06980052,  0.26384243,
        -0.11234827, -0.17317551, -0.08571427,  0.12835334,  0.18553674,
         0.11360297, -0.14117545, -0.13858776, -0.06508801, -0.09366166,
         0.11807271,  0.14160827, -0.01832087, -0.2664069 ,  0.08818354,
         0.04268969,  0.02134556, -0.09510548, -0.04879476, -0.33648625,
         0.20771468,  0.05423786,  0.14552316, -0.2

In [98]:
y_pred = rf.predict(document_vector('This is the 2nd time we have tried 2 contact u. U have won the £750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.').reshape(1,-1))

In [99]:
y_pred[0]

1